# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1401, 971))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(10, 0, 1201, 681))
        self.widget.setStyleSheet("background-image: url(:/main/PNG/bg.jpg);")
        self.widget.setObjectName("widget")
        self.balls_game_btn = QtWidgets.QPushButton(self.widget)
        self.balls_game_btn.setGeometry(QtCore.QRect(60, 20, 121, 111))
        self.balls_game_btn.setStyleSheet("border-image: url(:/main/PNG/game2.png) 0 0 0 0 stretch stretch;\n"
"background-size: cover;\n"
"border: none;\n"
"background-color: transparent;")
        self.balls_game_btn.setText("")
        self.balls_game_btn.setObjectName("balls_game_btn")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 140, 101, 41))
        self.label.setStyleSheet("color: white;\n"
"font-size: 13px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.snake_btn = QtWidgets.QPushButton(self.widget)
        self.snake_btn.setGeometry(QtCore.QRect(260, 20, 121, 111))
        self.snake_btn.setStyleSheet("border-image: url(:/main/PNG/game2.png) 0 0 0 0 stretch stretch;\n"
"background-color: transparent;\n"
"border: none")
        self.snake_btn.setText("")
        self.snake_btn.setObjectName("snake_btn")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(270, 140, 101, 41))
        self.label_2.setStyleSheet("color: white;\n"
"font-size: 13px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.flappy_btn = QtWidgets.QPushButton(self.widget)
        self.flappy_btn.setGeometry(QtCore.QRect(470, 20, 121, 111))
        self.flappy_btn.setStyleSheet("border-image: url(:/main/PNG/game2.png) 0 0 0 0 stretch stretch;\n"
"background-color: transparent;;\n"
"border: none")
        self.flappy_btn.setText("")
        self.flappy_btn.setObjectName("flappy_btn")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(480, 140, 101, 41))
        self.label_3.setStyleSheet("color: white;\n"
"font-size: 13px;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(950, 310, 231, 341))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.deposit_btn = QtWidgets.QPushButton(self.widget)
        self.deposit_btn.setGeometry(QtCore.QRect(950, 540, 111, 31))
        self.deposit_btn.setAutoFillBackground(False)
        self.deposit_btn.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);\n"
"")
        self.deposit_btn.setObjectName("deposit_btn")
        self.changepwd_btn = QtWidgets.QPushButton(self.widget)
        self.changepwd_btn.setGeometry(QtCore.QRect(950, 600, 111, 31))
        self.changepwd_btn.setAutoFillBackground(False)
        self.changepwd_btn.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);\n"
"")
        self.changepwd_btn.setObjectName("changepwd_btn")
        self.support_btn = QtWidgets.QPushButton(self.widget)
        self.support_btn.setGeometry(QtCore.QRect(1070, 540, 111, 31))
        self.support_btn.setAutoFillBackground(False)
        self.support_btn.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);\n"
"")
        self.support_btn.setObjectName("support_btn")
        self.logout_btn = QtWidgets.QPushButton(self.widget)
        self.logout_btn.setGeometry(QtCore.QRect(1070, 600, 111, 31))
        self.logout_btn.setAutoFillBackground(False)
        self.logout_btn.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);\n"
"")
        self.logout_btn.setObjectName("logout_btn")
        self.time_lcd = QtWidgets.QLCDNumber(self.widget)
        self.time_lcd.setGeometry(QtCore.QRect(1060, 470, 111, 51))
        self.time_lcd.setObjectName("time_lcd")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(960, 480, 101, 31))
        self.label_5.setAutoFillBackground(True)
        self.label_5.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(960, 420, 91, 41))
        self.label_6.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(960, 360, 91, 41))
        self.label_7.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.label_7.setObjectName("label_7")
        self.username_lb = QtWidgets.QLabel(self.widget)
        self.username_lb.setGeometry(QtCore.QRect(1030, 310, 91, 41))
        self.username_lb.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.username_lb.setObjectName("username_lb")
        self.balance_text = QtWidgets.QTextEdit(self.widget)
        self.balance_text.setGeometry(QtCore.QRect(1060, 360, 111, 41))
        self.balance_text.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.balance_text.setObjectName("balance_text")
        self.price_text = QtWidgets.QTextEdit(self.widget)
        self.price_text.setGeometry(QtCore.QRect(1060, 420, 111, 41))
        self.price_text.setStyleSheet("background-image: url(:/PNG/PNG/whitebg.png);")
        self.price_text.setObjectName("price_text")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bouncing Balls"))
        self.label_2.setText(_translate("MainWindow", "Snake"))
        self.label_3.setText(_translate("MainWindow", "Flappy bird"))
        self.deposit_btn.setText(_translate("MainWindow", "Nạp tiền"))
        self.changepwd_btn.setText(_translate("MainWindow", "Đổi mật khẩu"))
        self.support_btn.setText(_translate("MainWindow", "CSKH"))
        self.logout_btn.setText(_translate("MainWindow", "Đăng xuất"))
        self.label_5.setText(_translate("MainWindow", "Thời gian"))
        self.label_6.setText(_translate("MainWindow", "Giá máy"))
        self.label_7.setText(_translate("MainWindow", "Số dư"))
        self.username_lb.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

